# Build all images and run all containers
# `docker-compose -f docker-compose-local.yml up -d --build --force-recreate`

version: '3.7'

services:

  etd-alma-service:
    container_name: 'etd-alma-service'
    build:
      context: './'
      dockerfile: './DockerfileLocal'
    volumes:
      - './:/home/etdadm'
      - '/tmp:/tmp'
    env_file:
      - '.env'
    ports:
      # Worker API
      - '10601:8081'
    networks:
      - etd-net

# Create a custom docker network if it does not exist already
networks:
 etd-net:
    name: etd-net
